<html>
<body>

<h1>CARRITO</h1>

        <?php $cartItems= CartRepository::getItems($cart->getId()); ?>
        <?php if (isset($cartItems) && count($cartItems) > 0): ?>
            <?php foreach ($cartItems as $cartItem): ?>
                <div class="product-card">

                    <div class="product-image">
                        <img src="public/img/<?= $cartItem->getImage() ?>" alt="<?= $cartItem->getName() ?>">
                    </div>

                    <div class="product-info">
                        <h2>
                            <a href="index.php?c=product&action=viewProduct&id=<?= $cartItem->getId() ?>">
                                <?php echo $cartItem->getName(); ?>
                            </a>
                        </h2>

                        <p><?php echo $cartItem->getDescription(); ?></p>
                        <p class="price">Precio: $<?php echo $cartItem->getPrice(); ?></p>
                        <p class="stock">Stock: <?php echo $cartItem->getStock(); ?></p>

                        
                    </div>

                </div>


            <?php endforeach; ?>
        <?php else: ?>
            <p>No hay productos en el carrito.</p>
        <?php endif; ?>

<p><a href="index.php?c=product&action=volverTienda">Volver a la tienda</a></p>

</body>
</html>