<html>
<body>

<h1>CARRITO</h1>

<?php
    if (isset($cartItems) && count($cartItems) > 0) {
        foreach ($cartItems as $item) {
            echo "<li>" . $item->getName(); 
            echo "Precio: " . $item->getPrice() . "</li>";
        }
?>

<form action ="index.php?c=cart&action=pagarCarrito" method="POST">
    <input type="submit" value="Pagar carrito">
</form>

<?php
    } else {
        echo "<p>El carrito está vacío.</p>";
    }
?>

<p><a href="index.php?c=product&action=volverTienda">Volver a la tienda</a></p>

</body>
</html>