<html>
<body>

<h1>LOGIN</h1>

<form action="index.php?" method="POST">
<input type="text" name="username" placeholder="nombre de usuario">
<input type="password" name="password" placeholder="contraseña">
<input type="submit" value="Iniciar sesión">
</form>
<a href="index.php?c=user&action=register">¿No tienes cuenta? ¡Regístrate!</a>
<a class="login-link" href="index.php">Página principal</a>


</body>
</html>