<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mostrar Productos</title>
    <link rel="stylesheet" href="public/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">

</head>
<body>
    
    <header>
        <h1>🛍️ Bienvenido a la Tienda</h1>
    </header>

    <nav>
        <div class="nav-left">
            <form class="search-form" action="index.php?c=product&action=searchProduct" method="POST">
                <input type="text" name="q" placeholder="Buscar productos...">
                <button type="submit">🔍</button>
            </form>

            <ul class="main-menu">
                <li><a href="#"><i class="fa-solid fa-list"></i> Categorías</a></li>
                <li><a href="index.php?c=cart&action=showCart"><i class="fa-solid fa-cart-shopping"></i> Carrito</a></li>
                <li><a href="index.php?action=profile"><i class="fa-solid fa-user"></i> Perfil</a></li>
                <li><a href="index.php">Página principal</a></li>
                <?php if (UserRepository::isAdmin()) { ?>
                    <li><a href="index.php?c=product&action=showAddProduct">Añadir Producto</a></li>
                <?php } ?>
            </ul>
        </div>
        <?php if ($_SESSION['user'] === false) { 
            echo '  <ul class="auth-menu">
                        <li><a href="index.php?c=user&action=login">Iniciar Sesión</a></li>
                        <li><a href="index.php?c=user&action=register">Registrarse</a></li>
                    </ul>';
            }else{ 
                echo '  <ul class="auth-menu">
                            <li><a href="index.php?c=user&logout=1">Cerrar Sesión</a></li>
                        </ul>';
            }?>
    </nav>


    <main>
    <div class="products">
            <?php $products= ProductsRepository::showProductsInvisible();?>
            
        <?php if (isset($products) && count($products) > 0): ?>
            <?php foreach ($products as $product): ?>
                <div class="product-card">

                    <div class="product-image">
                        <img src="public/img/<?= $product->getImage() ?>" alt="<?= $product->getName() ?>">
                    </div>

                    <div class="product-info">
                        <h2>
                            <a href="index.php?c=product&action=viewProduct&id=<?= $product->getId() ?>">
                                <?php echo $product->getName(); ?>
                            </a>
                        </h2>

                        <p><?php echo $product->getDescription(); ?></p>
                        <p class="price">Precio: <?php echo $product->getPrice(); ?>€</p>
                        <p class="stock">Stock: <?php echo $product->getStock(); ?></p>
                        <?php 
                            if (UserRepository::isAdmin()) { 
                            echo '<a href="index.php?c=product&action=updateProduct&id='.$product->getId().'" class="add-to-cart">Editar Producto</a>';
                            echo '<a href="index.php?c=product&action=showProduct"';
                        } ?>
                        
                    </div>
                    
                </div>


            <?php endforeach; ?>
        <?php else: ?>
            <p>No hay productos ocultos.</p>
        <?php endif; ?>
    </div>
</main>

</body>
</html>

