<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalled de usuario</title>
    <link rel="stylesheet" href="public/css/style.css">
</head>
<body class="product-page">
    <header>
        <h1><?= $product->getName() ?></h1>
    </header>

    <a class="main-link" href="index.php">Página principal</a> 

    <div class="product-container">
        <div class="product-image">
            <img src="public/img/<?php 
            if($product->getImage()){
                echo ''. $product->getImage() .'';
            }else{
                echo 'default.png';
            }
            ?>" alt="<?= $product->getName() ?>">
        </div>
    </div>

    <div class ="product-info">
        <h2><?= $product->getName() ?></h2>
        <p><?php echo $product->getDescription(); ?></p>
        <p class="price">Precio: $<?php echo $product->getPrice(); ?></p>
        <p class="stock">Stock: <?php echo $product->getStock(); ?></p>

        <form action="index.php?action=addToCart&id=<?= $product->getId() ?>" method="POST">
            <input type="submit" name="addToCart" value="Añadir al carrito" class="add-to-cart-btn">
        </form>
    </div>

</body>
</html>