<html>
<body>

<h2><?= $product->getName() ?></h2>

<?php
    echo "Nombre del producto: ".$product->getName()."<br>";
    echo "Precio: ".$product->getPrice()."<br>";
    echo "Descripción: ".$product->getDescription()."<br>";
?>

<form action="index.php?c=product" method="POST">
    <input type="submit" name="addToCart" value="Añadir al carrito">
</form>

<p><a href="index.php?">Volver a la tienda</a></p>

</body>
</html>