<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalled de usuario</title>
    <link rel="stylesheet" href="public/css/style.css">
</head>
<body class="user-info-page">
    <header>
        <h1>Detalles de usuario</h1>
    </header>

    <a class="main-link" href="index.php">Página principal</a> 
    <a class="history-link" href="index.php?c=order&action=history">Mis Pedidos</a> 
    <div class="user-info-container">
        <img src="public/img/<?php if($_SESSION['user']->getAvatar()){
            echo ''.$_SESSION['user']->getUsername().''.$_SESSION['user']->getAvatar().'';
        }else{
            echo 'default.png';
        }
        ?>" alt="avatar">
        <h2><?php echo $_SESSION['user']->getUsername(); ?></h2>
        <p><?php echo $_SESSION['user']->getEmail(); ?></p>
        <a class="logout-link" href="index.php?logout=1">Cerrar sesión</a>
    </div>
    
</body>
</html>